### ISSUE TITLE
Infiniband and lower data size figures would be neat

### ISSUE THREAD

**Issue by monik3r** [abu-naser/CryptMPI-A-Fast-Encrypted-MPI-Library#1]
Hi, very interesting paper/project. I was looking through the arxiv paper and didn't seem to find any figures for message rates. I'm curious about what performance you got with 4k message sizes with the adapters in ib mode? Specifically I'm curious about message rates and latency (with the distribution). Forgive me if I misread the paper and missed similar figures.

Thanks!

**Comment by abu-naser** [comment]
Thank you for showing interest in our work. In this work, we have optimized the performance of the large message size, particularly 64KB and beyond. Hence, we skipped small size message performance in the paper. However, to answer your questions I have collected latency and message rate for the 4KB. The following data are collected on the Noleland cluster, using 2 nodes, 2 ranks, and on top of 100Gbs InfiniBand network. System specifications are described in the paper.

For the latency test, I have used [osu_latency](http://mvapich.cse.ohio-state.edu/benchmarks/), the results are as follows.
On 4KB message, Unencrypted average latency is 3.17 microseconds and CryptMPI's average latency is 5.99 microseconds.
For the message rate test, I have used [osu_mbw_mr](http://mvapich.cse.ohio-state.edu/benchmarks/) , and here reporting message rate is for 1 pair.
On 4KB message, Unencrypted average message rate is 1826286.74 messages/s and CryptMPI's average message rate is 465647.04 messages/s.

Currently, we are working to improve the performance of the message size <64KB and it will be out soon.
Hope, these answers your questions.
Thank you.

**Comment by monik3r** [comment]
Awesome, thank you so much for the quick and detailed reply! I totally understand focusing on 64k+ messages, it makes a good bit of sense. I'll play around a bit, thank you for open sourcing this project. Looking forward to testing things out :)
